src/Entity/Contracts.php
<?php

namespace App\Entity;

use App\Repository\ContractsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\BlameableTrait;
use App\Entity\Traits\TimestampableTrait;

#[ORM\Entity(repositoryClass: ContractsRepository::class)]
class Contracts
{ 
    use BlameableTrait;
    use TimestampableTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'contracts')]
    private ?Offers $offer = null;

    #[ORM\ManyToOne(inversedBy: 'contracts')]
    private ?User $collaborator = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $end_date = null;

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getOffer(): ?Offers
    {
        return $this->offer;
    }

    public function setOffer(?Offers $offer): static
    {
        $this->offer = $offer;

        return $this;
    }

    public function getCollaborator(): ?User
    {
        return $this->collaborator;
    }

    public function setCollaborator(?User $collaborator): static
    {
        $this->collaborator = $collaborator;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }
}

src/Controller/Back/ContractsController.php
<?php

namespace App\Controller\Back;

use App\Entity\Contracts;
use App\Form\ContractsType;
use App\Repository\ContractsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

#[Route('/contracts')]
class ContractsController extends AbstractController
{
    #[Route('/', name: 'app_contracts_index', methods: ['GET'])]
    public function index(ContractsRepository $contractsRepository, Security $security): Response
    {
        $user = $security->getUser();
        $contractsByCollaborator = $contractsRepository->findBy(
            ['collaborator' => $user]
        );
        $allContracts = $contractsRepository->findAll();

        $allowedRolesViewAllContracts = ['ROLE_COMMERCIAL', 'ROLE_RH', 'ROLE_ADMIN'];

        if (array_intersect($allowedRolesViewAllContracts, $user->getRoles())) {
            $contracts = $allContracts;
        } else {
            $contracts = $contractsByCollaborator;
        }
        return $this->render('back/contracts/index.html.twig', [
            'contracts' => $contracts
        ]);
    }

    #[Route('/new', name: 'app_contracts_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $contract = new Contracts();
        $form = $this->createForm(ContractsType::class, $contract);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($contract);
            $entityManager->flush();

            return $this->redirectToRoute('back_app_contracts_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/contracts/new.html.twig', [
            'contract' => $contract,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_contracts_show', methods: ['GET'])]
    public function show(Contracts $contract): Response
    {
        return $this->render('back/contracts/show.html.twig', [
            'contract' => $contract,
        ]);
    }

    #[Security('user === contract.getCreatedBy() or is_granted("ROLE_COMMERCIAL") or is_granted("ROLE_RH')]
    #[Route('/{id}/edit', name: 'app_contracts_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Contracts $contract, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ContractsType::class, $contract);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('back_app_contracts_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/contracts/edit.html.twig', [
            'contract' => $contract,
            'form' => $form,
        ]);
    }

    #[Security('user === contract.getCreatedBy() or is_granted("ROLE_COMMERCIAL") or is_granted("ROLE_RH')]

    #[Route('/{id}', name: 'app_contracts_delete', methods: ['POST'])]
    public function delete(Request $request, Contracts $contract, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $contract->getId(), $request->request->get('_token'))) {
            $entityManager->remove($contract);
            $entityManager->flush();
        }

        return $this->redirectToRoute('back_app_contracts_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/CooptationController.php
<?php

namespace App\Controller\Back;

use App\Entity\Cooptation;
use App\Entity\StepCooptation;
use App\Form\CooptationStepsType;
use App\Form\CooptationType;
use App\Repository\CooptationRepository;
use App\Repository\CooptationStepsRepository;
use App\Repository\StepCooptationRepository;
use App\Service\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;


#[Route('/cooptation')]
class CooptationController extends AbstractController
{
    #[Security('is_granted("ROLE_ADMIN") or is_granted("ROLE_RH") or is_granted("ROLE_COMMERCIAL")')]
    #[Route('/', name: 'app_cooptation_index', methods: ['GET'])]
    public function index(CooptationRepository $cooptationRepository): Response
    {
        return $this->render('back/cooptation/index.html.twig', [
            'cooptations' => $cooptationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_cooptation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $cooptation = new Cooptation();
        $form = $this->createForm(CooptationType::class, $cooptation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($cooptation);
            $entityManager->flush();

            if(!$this->isGranted('ROLE_RH')){
                return $this->redirectToRoute('back_default_index', [], Response::HTTP_SEE_OTHER);
            }else{
                return $this->redirectToRoute('back_app_cooptation_index', [], Response::HTTP_SEE_OTHER);
            }

        }

        return $this->renderForm('back/cooptation/new.html.twig', [
            'cooptation' => $cooptation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cooptation_show', methods: ['GET'])]
    public function show(Cooptation $cooptation): Response
    {
        return $this->render('back/cooptation/show.html.twig', [
            'cooptation' => $cooptation,
        ]);
    }

    #[Security('user === cooptation.getCreatedBy() or is_granted("ROLE_ADMIN") or is_granted("ROLE_RH")')]

    #[Route('/{id}/edit', name: 'app_cooptation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Cooptation $cooptation, EntityManagerInterface $entityManager, StepCooptationRepository $stepCooptationRepository, CooptationStepsRepository $cooptationStepsRepository): Response
    {
        $displayStatus = [];

        $allStepCooptations = $stepCooptationRepository->findAll();

        foreach ($allStepCooptations as $stepCooptation){
            $cooptationStepVerify = $cooptationStepsRepository->findBy([
                'cooptation' => $cooptation,
                'stepCooptation' => $stepCooptation
            ]);

            if(count($cooptationStepVerify) > 0){
                $displayStatus[$stepCooptation->getName()] = $cooptationStepVerify[0]->getStatus();
            }else{
                $displayStatus[$stepCooptation->getName()] = null;
            }
        }


        return $this->render('back/cooptation/edit.html.twig', [
            'stepCooptations' => $allStepCooptations,
            'cooptation' => $cooptation,
            'displayStatus' =>$displayStatus

        ]);


    }

    #[Security('user === cooptation.getCreatedBy() or is_granted("ROLE_ADMIN") or is_granted("ROLE_RH")')]
    #[Route('/{id}', name: 'app_cooptation_delete', methods: ['POST'])]
    public function delete(Request $request, Cooptation $cooptation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cooptation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($cooptation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('back_app_cooptation_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/CooptationStepsController.php
<?php

namespace App\Controller\Back;

use App\Entity\CooptationSteps;
use App\Form\CooptationStepsType;
use App\Repository\CooptationRepository;
use App\Repository\CooptationStepsRepository;
use App\Repository\StepCooptationRepository;
use App\Repository\UserRepository;
use App\Service\Mailer;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/cooptation/steps')]
class CooptationStepsController extends AbstractController
{

    private Mailer $mailer;

    public function __construct(Mailer $mailer)
    {
        $this->mailer = $mailer;
    }

    #[Route('/', name: 'app_cooptation_steps_new', methods: ['POST'])]
    public function handleCooptationSteps(
        Request $request,
        CooptationStepsRepository $cooptationStepsRepository,
        CooptationRepository $cooptationRepository,
        StepCooptationRepository $stepCooptationRepository,
        SessionInterface $session,
        UserRepository $userRepository
    ): Response
    {
        $availableStepCooptations = $stepCooptationRepository->findAll();

        $validStepCooptations = [];
        foreach ($availableStepCooptations as $stepCooptation) {
            $validStepCooptations[] = $stepCooptation->getId();
        }

        $data = $request->request->all();
        $stepCooptationId = $data['step_cooptation_id'];
        $stepCooptation = $stepCooptationRepository->find($data['step_cooptation_id']);
        $cooptation = $cooptationRepository->find($data['cooptation_id']);
        $collaborator = $cooptation->getCreatedBy();
        $status = $data['status'];

        if ($stepCooptationId == $validStepCooptations[0] || $cooptationStepsRepository->hasPreviousSteps($cooptation, $stepCooptation) ) {

            $cooptationStep = new CooptationSteps();
            $cooptationStep->setCooptation($cooptation);
            $cooptationStep->setStepCooptation($stepCooptation);
            $cooptationStep->setStatus($status);
            $cooptationStepsRepository->save($cooptationStep, true);

            if($stepCooptationId == end($validStepCooptations) && $status == 'validated'){
                $this->mailer->sendMailSuccessCoptationCollaborator($collaborator, $cooptation);
                $this->mailer->sendMailSuccessCoptationCandidate($cooptation);
                $collaborator->setPoints($collaborator->getPoints() + 10);
                $userRepository->save($collaborator, true);



            }
        } else {
            $session->getFlashBag()->add('error', 'Veuillez valider les étapes par ordre');

        }

        // Redirigez vers une autre page ou affichez un message de confirmation.
        return $this->redirectToRoute('back_app_cooptation_edit',['id' => $data['cooptation_id']]);
    }








}

src/Controller/Back/DefaultController.php
<?php

namespace App\Controller\Back;

use App\Repository\ContractsRepository;
use App\Repository\CooptationRepository;
use App\Repository\EventRegisterRepository;
use App\Repository\EventRepository;
use App\Repository\FormationRegisterRepository;
use App\Repository\FormationRepository;
use App\Repository\UserSkillsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;
use Symfony\UX\Chartjs\Model\Chart;


class DefaultController extends AbstractController
{
    #[Route('/', name: 'default_index', methods: ['GET'])]

    public function index(
        Security $security, ContractsRepository $contractsRepository, UserSkillsRepository $userSkillsRepository,
        EventRepository $eventRepository, FormationRepository $formationRepository, ChartBuilderInterface $chartBuilder,
        CooptationRepository $cooptationRepository, FormationRegisterRepository $formationRegisterRepository, EventRegisterRepository $eventRegisterRepository
    ): Response {
        $user = $security->getUser();
        $events = $eventRepository->findBy([], ['id' => 'DESC'], 3);
        $userSkills = $userSkillsRepository->findBy([
            'collaborator' => $user
        ]);
        $formations = [];

        foreach ($userSkills as $skill) {
            $formation = $formationRepository->findBy([
                'skill' => $skill->getSkill()
            ], [
                    'id' => 'DESC'
                ]);
            $formations = array_merge($formations, $formation);

        }
        usort($formations, function ($a, $b) {
            // Compare les IDs pour le tri (tri décroissant)
            return $b->getId() - $a->getId();
        });

        $threeFormations = array_slice($formations, 0, 3);


        $lastContract = $contractsRepository->findOneBy(
            [
                'collaborator' => $user,
            ],
            [
                'id' => 'DESC'
            ]
        );

        $cooptationsChart = $cooptationRepository->count([
            'createdBy' => $user
        ]);

        $formationsChart = $formationRegisterRepository->count([
            'collaborator' => $user
        ]);

        $eventChart = $eventRegisterRepository->count([
            'collaborator' => $user
        ]);

        $chart = $chartBuilder->createChart(Chart::TYPE_DOUGHNUT);

        $chart->setData([
            'labels' => ['Cooptation crées', 'Formation suivies', 'Événement suivis'],
            'datasets' => [
                [
                    'label' => 'Mes activités',
                    'backgroundColor' => [
                        'rgb(255, 99, 132)',
                        'rgb(54, 162, 235)',
                        'rgb(255, 205, 86)'
                    ],
                    'data' => [$cooptationsChart, $formationsChart, $eventChart],
                ],
            ],
        ]);

        return $this->render('back/default/index.html.twig', [
            "user" => $user,
            "lastContract" => $lastContract,
            "formations" => $threeFormations,
            "events" => $events,
            'chart' => $chart
        ]);
    }
}

templates/back/contracts/_delete_form.html.twig
<form method="post" action="{{ path('back_app_contracts_delete', {'id': contract.id}) }}" onsubmit="return confirm('Es-tu sûr de vouloir supprimer ce contrat?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contract.id) }}">
    <button class="btn devisio-btn-delete">Supprimer</button>
</form>

templates/back/contracts/_form.html.twig
<div class="h-[90%]">
	<a class="devisio-btn devisio-btn-back-to-list" href="{{ back_to_list_path|default(path('back_app_contracts_index')) }}">
		Retourner à la liste
	</a>
	  <h1 class="text-center text-xl font-bold">
  {% if form.vars.value.id is not null %}
        Modification le contrat
    {% else %}
      Ajouter un contrat
    {% endif %}
</h1>
	<div class="flex justify-center items-center h-full">
		{{ form_start(form, {'attr': {'class': 'w-[40%] py-9 px-9 rounded bg-white', 'style': 'border: 1px solid white;'}}) }}

		{{ form_widget(form) }}
		<button class="bg-[#5B98D2] hover:bg-blue-700 text-white font-bold py-4 px-4 rounded">
			{{ button_label|default('Sauvegarder') }}
		</button>
		{{ form_end(form) }}
	</div>

</div>

templates/back/contracts/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contrat{% endblock %}

{% block body %}

    {{ include('back/contracts/_form.html.twig', {'button_label': 'Update'}) }}

{% endblock %}

templates/back/contracts/index.html.twig
{% extends 'base.html.twig' %}
{% import 'components/components.html.twig' as components%}

{% block title %}Contrat {% endblock %}

{% block body %}
    <div class="list-wrapper">
        {% if is_granted('ROLE_COMMERCIAL') or is_granted('ROLE_RH')  %}
            <a href="{{ path('back_app_contracts_new') }}" class="devisio-btn devisio-btn-add">
                Nouveau contrat
            </a>
        {% endif %}
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Offre</th>
                    <th>Entreprise</th>
                    <th>Collaborateur</th>
                    <th>Date de début</th>
                    <th>Date de fin</th>
                    {% if is_granted('ROLE_COMMERCIAL') or is_granted('ROLE_RH')  %}
                         <th>actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
            {% for contract in contracts %}
                <tr>
                    <td>{{ contract.id }}</td>
                    <td>{{ contract.offer.name }}</td>
                    <td>{{ contract.offer.companyName }}</td>
                    <td>{{ contract.collaborator.firstname   ~ ' ' ~  contract.collaborator.lastname }}</td>
                    <td>{{ contract.startDate|date('d-m-Y') }}</td>
                    <td>{{ contract.endDate|date('d-m-Y') }}</td>
                    {% if is_granted('ROLE_COMMERCIAL') or is_granted('ROLE_RH')  %}
                        <td>{{ components.table_actions('contracts', contract) }}</td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/back/contracts/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contrat{% endblock %}

{% block body %}
 

    {{ include('back/contracts/_form.html.twig') }}

{% endblock %}

templates/back/contracts/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contrat{% endblock %}

{% block body %}
    <div class="show-wrapper">
        <h1>Contracts</h1>
        <a class="devisio-btn devisio-btn-back-to-list" href="{{ path('back_app_contracts_index') }}">Retour à la liste</a>

        <table >
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ contract.id }}</td>
                </tr>
                <tr>
                    <th>Offre</th>
                    <td>{{ contract.offer.name }}</td>
                </tr>
                <tr>
                    <th>Entreprise</th>
                    <td>{{ contract.offer.companyName }}</td>
                </tr>
                <tr>
                    <th>Collaborateur</th>
                    <td>{{ contract.collaborator.firstname   ~ ' ' ~  contract.collaborator.lastname }}</td>
                </tr>
                <tr>
                    <th>Date de début </th>
                    <td>{{ contract.startDate|date('d-m-Y') }}</td>
                </tr>
                <tr>
                    <th>Date de fin</th>
                    <td>{{ contract.endDate|date('d-m-Y') }}</td>
                </tr>
            </tbody>
        </table>
        <div class="show-buttons">
            {{ include('back/contracts/_delete_form.html.twig') }}
            <a class="devisio-btn devisio-btn-update" href="{{ path( 'back_app_contracts_edit', { id: contract.id } ) }}">Modifier</a>
        </div>
    </div>

{% endblock %}